{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosArm64Main-1.0.3.klib",
          "url": "kni-api-iosarm64-1.0.3.klib",
          "size": 311814,
          "sha512": "5195495cd53447a26c6ff571c1ae91dce818497d64dce441dd6d60fbe2dff7ebd7c1027141967720faa5a32e42ec1b22038aa9fec1acac9c78ae05a911e4579f",
          "sha256": "a3e5fcc88b6800c997a00a1e034b1ab03e1c0282ad572f8b81fa327985d23689",
          "sha1": "b32fbb32c196d2a92b83218fd7f2e89048a34f6a",
          "md5": "a85627870bbf20c46e876c4ae0449a08"
        },
        {
          "name": "kni-api-iosArm64Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-iosarm64-1.0.3-cinterop-jni.klib",
          "size": 16372,
          "sha512": "bc8ddb3b97b1fda987992d8dc75bf0e7ce2f0206239167053059b7d345ab444a57744b7d14e0e58fc391d5d93af902243fa34212ca723a45e1d6895a56ad5093",
          "sha256": "b47df33abf013a1a2d9a32ef63c10f46d22bf5318004f8aad0988b1eb97710fc",
          "sha1": "7283bc3a8a89cc9cbd9fd2cad5360c1b778675e7",
          "md5": "cbdb7def97f15d5da25318f2af01626e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iosarm64-1.0.3-sources.jar",
          "url": "kni-api-iosarm64-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosarm64-1.0.3-metadata.jar",
          "url": "kni-api-iosarm64-1.0.3-metadata.jar",
          "size": 33701,
          "sha512": "cebff3d219a775beeb73b1c77b03e6dcd7387509abbac1bd63ae14ae9b19234ef5087e912fab308c4b5c3ae9665aaa99c9cf01266ea20941a517a3ac0e844fb8",
          "sha256": "edfd24c7c921c147cced09e3c64ae6a51cb3661b41fc5718555064286043a289",
          "sha1": "9373a373f087d245b7758439fbe9586f8985815a",
          "md5": "c4a65a73fb0ad650aedf8c20478b1011"
        }
      ]
    }
  ]
}
