{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosArm64Main-1.0.2.klib",
          "url": "kni-api-iosarm64-1.0.2.klib",
          "size": 317629,
          "sha512": "1335d14bd677e792fd1ff83d5a480bcc62912bd8caa9c1500bd7d43ba7fde86c615f39d2f49fe9b2d965e27fa4eb23e65cb7fd2c87f8519ed7c2db410c7b7d3a",
          "sha256": "3abe29509a9314f3e21e4f2fd05e3c8571e30991367e725dfe761e6363171544",
          "sha1": "7cd31e66c4e0cd7439f07db838781dc466cac8e2",
          "md5": "b59316f8811d55e22c208fc275cea891"
        },
        {
          "name": "kni-api-iosArm64Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-iosarm64-1.0.2-cinterop-jni.klib",
          "size": 16370,
          "sha512": "1fa9edd9e30ef2b3645465976e98502981ca625f8555873774fb2cd4d8c2914dc18928dff3c37c6979c10c98eb851f37aebd9eabb56d014d199ca8143962b8fd",
          "sha256": "51c1e835573692dd86cf254ebef50e25c32fc58f591289f2d7b6ffeebfb3d43e",
          "sha1": "3171d94bbcdc4e0039cf021d81fae2bba26bea79",
          "md5": "d4cbcfc97c84949b992e71a301f97a77"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iosarm64-1.0.2-sources.jar",
          "url": "kni-api-iosarm64-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosarm64-1.0.2-metadata.jar",
          "url": "kni-api-iosarm64-1.0.2-metadata.jar",
          "size": 33688,
          "sha512": "d45b0639f240a5ba91e873460c1f2a26931cdf60468cb4a6b512cd9261eec78a4da15a9cb35f97cf526cb1e5357df702aafd5089b11a76acf427452af1606587",
          "sha256": "9b9e26be1390dde6b088fcc776c4d06489d277a572317ec62d713d34f1f1a6be",
          "sha1": "ce75eef08cc8f482e7934258964acb29963764b1",
          "md5": "d44f3a04ff33a5eb1d5d1392c964144f"
        }
      ]
    }
  ]
}
