{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "service",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "nio",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api.aar",
          "url": "kni-api-android-1.0.3.aar",
          "size": 89570,
          "sha512": "76602675d1c827235d629849887fb7687b1cdd70d34b671685e5bfe9abd6b7a023c5b958c66cad11ca95f23ca7aa987fb48ae84390409de82c4b36ef25acce17",
          "sha256": "232501ff43d3bc10c9f339f42dc8c44396b2002f4a2e1898f8cd01efb13c78b2",
          "sha1": "0cfc2df590e25fe25027ee5c883364584c8b37bc",
          "md5": "49fa09c5a3055a0b327f70492df58d1b"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "service",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "nio",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.github.dreammooncai.yukireflection",
          "module": "api-kotlin",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api.aar",
          "url": "kni-api-android-1.0.3.aar",
          "size": 89570,
          "sha512": "76602675d1c827235d629849887fb7687b1cdd70d34b671685e5bfe9abd6b7a023c5b958c66cad11ca95f23ca7aa987fb48ae84390409de82c4b36ef25acce17",
          "sha256": "232501ff43d3bc10c9f339f42dc8c44396b2002f4a2e1898f8cd01efb13c78b2",
          "sha1": "0cfc2df590e25fe25027ee5c883364584c8b37bc",
          "md5": "49fa09c5a3055a0b327f70492df58d1b"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kni-api-android-1.0.3-sources.jar",
          "url": "kni-api-android-1.0.3-sources.jar",
          "size": 18690,
          "sha512": "827105671b6aecaed404a5ab4da010877d4ed7a96e82e366b75b317058d9deee370e365ff54c03c7afdc52815c1b875dfd6c7d5b8cc7eaf8afcdcf2a09a47700",
          "sha256": "ecf49f343b5a2e203b10a132c94ac9c3ec3ff0d3fb887229422e1babe82f4102",
          "sha1": "474f7d407d9b6bc72c6727a8a9d7c05868a6b38b",
          "md5": "afb7075f5dabf9dfe8e2d79439b5432d"
        }
      ]
    }
  ]
}
