{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.1/kni-api-1.0.1.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeArm32Main-1.0.1.klib",
          "url": "kni-api-androidnativearm32-1.0.1.klib",
          "size": 314090,
          "sha512": "cdca0cb38480f60fa6396664643aa8a0faf727301725f2e8b815463507c4c8877aea07d639f41ce53cc0d38e9eeed001f670dd8fb58e77895ac08720cac5e2c7",
          "sha256": "3aeb9aff21680dbaa83457d098ae1643101ec0d2ea6bf4cde740d3041b41b154",
          "sha1": "7f660e71de105dc1360b36b2b59050b1c8d389ea",
          "md5": "5f77918feafa2a010da947be2e009349"
        },
        {
          "name": "kni-api-androidNativeArm32Cinterop-jniMain-1.0.1.klib",
          "url": "kni-api-androidnativearm32-1.0.1-cinterop-jni.klib",
          "size": 16635,
          "sha512": "9716a202fb8826b18564fef22eaff7aae2f0727b00a95b5175dac9e6b09028c86ed98752fb8fb5a38ed1bc60ccad4bbd1fbf73a4f5488df16c1e45125157b38d",
          "sha256": "c3cb795bea208f25526c00e35f839e679111713d52ab8952f230991f02fe3f7c",
          "sha1": "b400f361c6e76636406a8f828aca54c8a554c23b",
          "md5": "df0ea5e74712aa3d063412d7d48fc24a"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativearm32-1.0.1-sources.jar",
          "url": "kni-api-androidnativearm32-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "5bbb9c63d40f26289ac620c83bc4af3498a2640b886c5e02070220397299dc2d4231f374d06bb3534290f5b750c6124510fbb9351ba3e505544ba17f8eedf561",
          "sha256": "6af75a865ba406e04cc85a3debe889812302cf880f589689447617b8a5a450f2",
          "sha1": "13c9dd629bcd18808fb03a680125e21676332fa9",
          "md5": "e0222a14c24a77f52c50a994f198e1ae"
        }
      ]
    }
  ]
}
