{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosArm64Main-1.0.3.klib",
          "url": "kni-api-macosarm64-1.0.3.klib",
          "size": 311828,
          "sha512": "930def31c90980b78a99059fa7b426347394a70514f2bad53e940fd06a7dce1a702052406cba439f30607ce38683bb3bb5447021ee2317a9f30f92778276fb65",
          "sha256": "3929eda66d2e61087b51eb2c2d9ea8592c46a9ce6117fccf49025ee6e35f6c59",
          "sha1": "05591c623600e1e2e0f692e17dafb4972a51dab5",
          "md5": "90b706143f1d450177ab6b5c0b381e3d"
        },
        {
          "name": "kni-api-macosArm64Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-macosarm64-1.0.3-cinterop-jni.klib",
          "size": 16703,
          "sha512": "1e897ab49784ab6e4eefcf4b30af6beedfbc67db0d426ef9fe6596ef21684932c68775d5a2f9cf9db12fa995367caa10c885a8d96bb71b35f45e49b44927c021",
          "sha256": "56ca6253ebede65f6d4793eb03297c0ea81c2e635195d99304e7a4910e8590ec",
          "sha1": "62a872ca58a18db9299d7a4db11ea9f8de44b4c3",
          "md5": "52bf150566a42b2593e25f5baa1ee16d"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-macosarm64-1.0.3-sources.jar",
          "url": "kni-api-macosarm64-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosarm64-1.0.3-metadata.jar",
          "url": "kni-api-macosarm64-1.0.3-metadata.jar",
          "size": 33701,
          "sha512": "cebff3d219a775beeb73b1c77b03e6dcd7387509abbac1bd63ae14ae9b19234ef5087e912fab308c4b5c3ae9665aaa99c9cf01266ea20941a517a3ac0e844fb8",
          "sha256": "edfd24c7c921c147cced09e3c64ae6a51cb3661b41fc5718555064286043a289",
          "sha1": "9373a373f087d245b7758439fbe9586f8985815a",
          "md5": "c4a65a73fb0ad650aedf8c20478b1011"
        }
      ]
    }
  ]
}
