{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosX64Main-1.0.2.klib",
          "url": "kni-api-macosx64-1.0.2.klib",
          "size": 317630,
          "sha512": "57bd56b0d0089f6dc43830e2d913eb942092164036548e01dce20bf3c4ef58374da776ff75cd6cf142ea0623171319a9cb1d767cef954fcb9a3188f633f029eb",
          "sha256": "029c66c133a63bbbaf1c877c3492cf51c71e5d31071ab778e84b89cc436a0663",
          "sha1": "6087caf3fd71ed11669d1874faa247fba54e1007",
          "md5": "1e90f440050c68bcd1dea52afa9042ed"
        },
        {
          "name": "kni-api-macosX64Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-macosx64-1.0.2-cinterop-jni.klib",
          "size": 16430,
          "sha512": "63dd5659c58cca7385487e3575228c9d48b3b2112b1c8f9ff7fa0c816596d40984cd7d870180d9e5896564f0e53420015afc44d7f2e7006c2ce770c106fbf5d5",
          "sha256": "6851f4a7f91a83873fcff5350c7725a34729d5ef44b4b9f1321bb284cc15f17d",
          "sha1": "32fb3712f415f9a2db894a08f6b0702db544b1c9",
          "md5": "a3b3860b6daeb77b37539833b291f10d"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-macosx64-1.0.2-sources.jar",
          "url": "kni-api-macosx64-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosx64-1.0.2-metadata.jar",
          "url": "kni-api-macosx64-1.0.2-metadata.jar",
          "size": 33688,
          "sha512": "6bc1b48d85a86a349f2a5a0822e7cd1ee6d88e08d2a0ae03444703242e437226fa0a737c928841096c2549eab56628bbb51ffdb7301e418ca5dc298624e4c3d0",
          "sha256": "c0ea6b6c5a28a3a92212ee070240c1a07c0d99751b4762f4479c2a2b6459798b",
          "sha1": "0da63912111c0fff9394593d7fd30077ca2913ae",
          "md5": "ecd1d792514190ad5095b36efe01fc12"
        }
      ]
    }
  ]
}
