{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.1/kni-api-1.0.1.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosArm64Main-1.0.1.klib",
          "url": "kni-api-iosarm64-1.0.1.klib",
          "size": 314065,
          "sha512": "917176a5301a3a25f7f9034a780dcd19b4e75bab47c5fdd5c5a8adc0b1c6a9fa6c7681c32e879dd34ddef19ef72b3b35c7b930f5cf082eb1e8ac87cba667f127",
          "sha256": "3fda9fa53b1831073e480d95fff958b5323f415ca0714978b19315fd55cfa074",
          "sha1": "6138b704bcd95fcb7070f21b014f31f44df526d6",
          "md5": "220b43f18f82fa5b734aece3b58a16d2"
        },
        {
          "name": "kni-api-iosArm64Cinterop-jniMain-1.0.1.klib",
          "url": "kni-api-iosarm64-1.0.1-cinterop-jni.klib",
          "size": 16370,
          "sha512": "1fa9edd9e30ef2b3645465976e98502981ca625f8555873774fb2cd4d8c2914dc18928dff3c37c6979c10c98eb851f37aebd9eabb56d014d199ca8143962b8fd",
          "sha256": "51c1e835573692dd86cf254ebef50e25c32fc58f591289f2d7b6ffeebfb3d43e",
          "sha1": "3171d94bbcdc4e0039cf021d81fae2bba26bea79",
          "md5": "d4cbcfc97c84949b992e71a301f97a77"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iosarm64-1.0.1-sources.jar",
          "url": "kni-api-iosarm64-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "5bbb9c63d40f26289ac620c83bc4af3498a2640b886c5e02070220397299dc2d4231f374d06bb3534290f5b750c6124510fbb9351ba3e505544ba17f8eedf561",
          "sha256": "6af75a865ba406e04cc85a3debe889812302cf880f589689447617b8a5a450f2",
          "sha1": "13c9dd629bcd18808fb03a680125e21676332fa9",
          "md5": "e0222a14c24a77f52c50a994f198e1ae"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosarm64-1.0.1-metadata.jar",
          "url": "kni-api-iosarm64-1.0.1-metadata.jar",
          "size": 33685,
          "sha512": "87095ab2fac440b6fdd7040570add2630dfa6b8d6b7a725be66e4340557b0ad02f23c6b09fb94d815daf015e4c9525dc67911a119675d3a447ed2d38743036c9",
          "sha256": "31b3790ae32df219fba84052223c8c62d163cc0615f430a3a4bf57d5c9a26441",
          "sha1": "333ac370b41d43343104659dfdbaa705525853f4",
          "md5": "bbbb1707fb772d6cafcc50c4a3f07962"
        }
      ]
    }
  ]
}
