{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosX64Main-1.0.3.klib",
          "url": "kni-api-macosx64-1.0.3.klib",
          "size": 311815,
          "sha512": "22acc0d4a6483347fbb058f1236c67bfb2dc694541036048d4fa11dcac9bc653ae16a2211fad6c68774b76986cc6a8977dd23da80475178f37f027df7fc21a2e",
          "sha256": "f4b6c04a6f2ae15ec55c7fadfce870e3ee183441fd82fc68edbf07312b2c47d9",
          "sha1": "8e8c504f524802e4057e35c14692b6cab297c555",
          "md5": "841be71adc02bc2ca04337f3461b6596"
        },
        {
          "name": "kni-api-macosX64Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-macosx64-1.0.3-cinterop-jni.klib",
          "size": 16432,
          "sha512": "18ebe54bd67668ea9b3b3d723548e28d37ca92d59827f07e156d9753de8efefc1e0ccb236d705e96fa0605e8f384f068c0943ccfbc981d1441f98a83d8915c5b",
          "sha256": "aa16e10c222bfe3fbd96c2f08ebf0b0574f61906efc80f1512962b5aefa3bf68",
          "sha1": "26c45696b58d2f6a606966df6f55d109930bb18f",
          "md5": "fc71a7b22f8c302510947258ad1baec2"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-macosx64-1.0.3-sources.jar",
          "url": "kni-api-macosx64-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosx64-1.0.3-metadata.jar",
          "url": "kni-api-macosx64-1.0.3-metadata.jar",
          "size": 33701,
          "sha512": "cebff3d219a775beeb73b1c77b03e6dcd7387509abbac1bd63ae14ae9b19234ef5087e912fab308c4b5c3ae9665aaa99c9cf01266ea20941a517a3ac0e844fb8",
          "sha256": "edfd24c7c921c147cced09e3c64ae6a51cb3661b41fc5718555064286043a289",
          "sha1": "9373a373f087d245b7758439fbe9586f8985815a",
          "md5": "c4a65a73fb0ad650aedf8c20478b1011"
        }
      ]
    }
  ]
}
