{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeArm32Main-1.0.3.klib",
          "url": "kni-api-androidnativearm32-1.0.3.klib",
          "size": 311833,
          "sha512": "bb948015e96918fb2d7e0df236103fa56303eb27f803c47a28e28b4f061e16508edc7cb913653da1a11996acb167988e3a1048c7bb013742a94e5e7aec105542",
          "sha256": "fac6239b73f8afab0d09a398b941a84704f7cee28dad29dbf5334457dfa093e3",
          "sha1": "122088a9a7359b3c4c59e623527f69db862e081b",
          "md5": "8c3838835a8db3a295ff5f7b3bb535fa"
        },
        {
          "name": "kni-api-androidNativeArm32Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-androidnativearm32-1.0.3-cinterop-jni.klib",
          "size": 16637,
          "sha512": "aa6c9d9e37b0020b7376e045261de173113da0b7843a76bc01bcedfdc4c1634e93aed1b55497a08a6a660618a59bf6ac439d007c7a93713ee354caf05b60eab1",
          "sha256": "39a69d94d94ec1e6a6beb6bb53bb969c5d4fc09865eb8560533dc360f3fda63b",
          "sha1": "c9cb24db708d61d5395e9851bbbaf5f12e5419fc",
          "md5": "82eef13452926306e33cf7b0532652da"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativearm32-1.0.3-sources.jar",
          "url": "kni-api-androidnativearm32-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
