{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.1/kni-api-1.0.1.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosArm64Main-1.0.1.klib",
          "url": "kni-api-macosarm64-1.0.1.klib",
          "size": 314079,
          "sha512": "ba2c6b1b2c12685b8aac79b4a53fdc1c7235678533b18a4dbcc4d3e2c8b5460fb69f4422a45e99bc2ab702903f9f1e3ee93c79330cfd6b94af3018bf4ac29638",
          "sha256": "8e400fede714e2d55f64d4658490079df4358b6f5e4a261d8f1862f31efd691b",
          "sha1": "3d738787e916e837dfdef05821b621c90e19417b",
          "md5": "b8eece77663958fe856572f837e66bc8"
        },
        {
          "name": "kni-api-macosArm64Cinterop-jniMain-1.0.1.klib",
          "url": "kni-api-macosarm64-1.0.1-cinterop-jni.klib",
          "size": 16701,
          "sha512": "ab8426bc266927e8a5c93c15f967436b0ec80bd8603b7ad9ed422e8ae86065aa0e68fbb80f2a79eaacebc1e98ad9e61015fbcb9aac22bc683841f6addbccf63e",
          "sha256": "8e4ba882dff494a8131c3274574d4cb28d009a265d3e248c7b7f63d9b18eb6c0",
          "sha1": "f457aac1bb6fcd9131148f54af62affc6ec94837",
          "md5": "d396ec3efc1be06706db2efe7081b8a1"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-macosarm64-1.0.1-sources.jar",
          "url": "kni-api-macosarm64-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "5bbb9c63d40f26289ac620c83bc4af3498a2640b886c5e02070220397299dc2d4231f374d06bb3534290f5b750c6124510fbb9351ba3e505544ba17f8eedf561",
          "sha256": "6af75a865ba406e04cc85a3debe889812302cf880f589689447617b8a5a450f2",
          "sha1": "13c9dd629bcd18808fb03a680125e21676332fa9",
          "md5": "e0222a14c24a77f52c50a994f198e1ae"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosarm64-1.0.1-metadata.jar",
          "url": "kni-api-macosarm64-1.0.1-metadata.jar",
          "size": 33685,
          "sha512": "1392693af405d29ac392b4d5a36366d0c7fb745f9103dacd5175a7f803e87a3e7f1ffc1daa82f50a153e2d902eb9d4313e273c9a1de6b42116ca8be061635ff3",
          "sha256": "9732380376d75ffb0095e4c4cbb7dc28bb65e74cf105df9759fa9b49179d6494",
          "sha1": "259e6084ff6c021aa91deace367b4cc7ab99a9cb",
          "md5": "c62aab067c40c91532becdeda00c22bb"
        }
      ]
    }
  ]
}
