{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-windowsMain-1.0.2.klib",
          "url": "kni-api-windows-1.0.2.klib",
          "size": 317607,
          "sha512": "be8e12bf0706baae17a8d1d2ac1b3430edc1ceaa0b66e49179b6e53517702944e937d44644286b7cce1f631959bd926a055606e2db3417ed9a91dc9729efb647",
          "sha256": "388d7774c2160ce54cf1435b7a8619e76c2a5aab2261c04642b10224e22c71ad",
          "sha1": "3da3e6968946a8f4c5f3a50ecfebc00148d424ec",
          "md5": "153cd288f02f965a07fae2e5b8df7ba6"
        },
        {
          "name": "kni-api-windowsCinterop-jniMain-1.0.2.klib",
          "url": "kni-api-windows-1.0.2-cinterop-jni.klib",
          "size": 16156,
          "sha512": "ab9fa6a3ced79b3fdab1a185882e5e61caccecd609315baf55abaed617d3e152d2a60eea4917298925def2afc4f24aa39d114965e3a35d2d7441ad4b268167fd",
          "sha256": "eff895e4da6172175693cb839ddd7f5d163b9126dda844697999040ae1223a4f",
          "sha1": "c42cbc1c702df2615887714b03ea548d0b979218",
          "md5": "43bbcb3d7df006b151d32e647b3572fe"
        }
      ]
    },
    {
      "name": "windowsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-windows-1.0.2-sources.jar",
          "url": "kni-api-windows-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
