{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-metadata-1.0.3.jar",
          "url": "kni-api-1.0.3.jar",
          "size": 68586,
          "sha512": "193955c368450386e903c813b34e1b1fd2708e649be0b722305cdd9ca8c357534da4669ab8e618b0e961413d32cb3f86bdfc89822e371284772669ea65c84137",
          "sha256": "d0ba133297e73f3226cd4a9ced6582571bbfd99628c32dd82665625ec2ce2a95",
          "sha1": "9b5bca514eb3356701ba265057c839d67b256cc5",
          "md5": "9e77bc5ef5717161f5d7dc2bfb5b91e0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kni-api-kotlin-1.0.3-sources.jar",
          "url": "kni-api-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "b7b0079ffd57136c5e9895d1462de8e58d803897d06f37103b5c5c6c0a9dfaa9cee85c623072353f92550f3d7d358937751be37499a165c2846176ef7704c087",
          "sha256": "8a95837d938ebdc87badbebdf0613769f5de2d5e0e0dde9d2242fac41c074868",
          "sha1": "7a24701bf77a101e67cc98e0208aa21dace93245",
          "md5": "b4f494f6afae3160d0c0595b06b763ad"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.3/kni-api-android-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.3/kni-api-android-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.3/kni-api-android-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm32/1.0.3/kni-api-androidnativearm32-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm32",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm32/1.0.3/kni-api-androidnativearm32-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm32",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm64/1.0.3/kni-api-androidnativearm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm64/1.0.3/kni-api-androidnativearm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex64/1.0.3/kni-api-androidnativex64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex64",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex64/1.0.3/kni-api-androidnativex64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex64",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex86/1.0.3/kni-api-androidnativex86-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex86",
        "version": "1.0.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex86/1.0.3/kni-api-androidnativex86-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex86",
        "version": "1.0.3"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.3/kni-api-desktop-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.3"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.3/kni-api-desktop-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.3"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.3/kni-api-desktop-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.3/kni-api-iosarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.3/kni-api-iosarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.3/kni-api-iosarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.3/kni-api-iossimulatorarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.3/kni-api-iossimulatorarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.3/kni-api-iossimulatorarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.3/kni-api-iosx64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.3/kni-api-iosx64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.3/kni-api-iosx64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.3/kni-api-macosarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.3/kni-api-macosarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.3/kni-api-macosarm64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.3/kni-api-macosx64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.3/kni-api-macosx64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.3/kni-api-macosx64-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.3"
      }
    },
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-windows/1.0.3/kni-api-windows-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-windows",
        "version": "1.0.3"
      }
    },
    {
      "name": "windowsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-windows/1.0.3/kni-api-windows-1.0.3.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-windows",
        "version": "1.0.3"
      }
    }
  ]
}
