{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosX64Main-1.0.2.klib",
          "url": "kni-api-iosx64-1.0.2.klib",
          "size": 317616,
          "sha512": "bd0829cef5427507a4c9fcaf544565370e6b9b075f021001ffc2ac7e5fd43043138074b2be9da31394f4b67649e74656733730cb60fc8bae17ae0713c43cd776",
          "sha256": "cdc4e430d8bb62d0c9108c9595586afdff9dad8aeb7afa7867814789d92b882b",
          "sha1": "ed9db2096242980aa6e383160bc5ec2435664526",
          "md5": "f73e04220f8501481b8ea0f4a440c720"
        },
        {
          "name": "kni-api-iosX64Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-iosx64-1.0.2-cinterop-jni.klib",
          "size": 16410,
          "sha512": "2130a1c0fab572f1578d0ed5f1d0534873f559ac737b3b03aa9a4c8eeb89cc605212af4da239cb108b0202c0fbe31a194a3df8e7e3ec6036155755943e9c5f54",
          "sha256": "720523ba13c1083b802f04445c35c82c37acf22de67d6261514d009840794905",
          "sha1": "93dc403a4b5d044dbaf2a4b6148279cd6342dc18",
          "md5": "e498b705562ce020e7d129604b26fcd0"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iosx64-1.0.2-sources.jar",
          "url": "kni-api-iosx64-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosx64-1.0.2-metadata.jar",
          "url": "kni-api-iosx64-1.0.2-metadata.jar",
          "size": 33688,
          "sha512": "486e4dec69f71eada0062fec0365acb0159e475efde8cc1487811bfc8208411e0c7c38715981d38a76389327ee767285de93268f6a3bb8c52e50d74c1b911ea4",
          "sha256": "8694ed721278bc65f39839a9d8f01de09dce65274c05c97ac2c20a8749fc556f",
          "sha1": "4d93e26bd0ae9bc90f0ad9ff2faf96576afc219b",
          "md5": "7f641350d9bf5fe7eb36b8569d4c1645"
        }
      ]
    }
  ]
}
