{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-windowsMain-1.0.3.klib",
          "url": "kni-api-windows-1.0.3.klib",
          "size": 311786,
          "sha512": "5986c16f9d33d3ebb55c0c0b9113652aa1c0e1c4814a0c1a676911126028d45e5c3a3a81ee95df782faede0a1dc7da2da9b8a6046b10609f5a96baee1ee1ef18",
          "sha256": "daf565a14555fe8411fcaa5fec35b8cec4e0b4c59b7b475924d424fc6b2c1752",
          "sha1": "63e717193ac26e440ab0890a4ffb6611f533bb2b",
          "md5": "80f2ca16e9853ff36a8af755e42aba8c"
        },
        {
          "name": "kni-api-windowsCinterop-jniMain-1.0.3.klib",
          "url": "kni-api-windows-1.0.3-cinterop-jni.klib",
          "size": 16158,
          "sha512": "2c61a7632930cb7a5e5a07f9188d5f84a3b24fe36b39b05151bd1fc2d1da4a7ef7df1ee3cde280495b036026ea58af927510fa6d17503dc61543345d16a11c9a",
          "sha256": "f73ada83021f3cae8cebca701e732c4d5126f07ccd51ff1578f1c7d45b791cb7",
          "sha1": "5aa99791b8abaa2f9e08f189e11143dcfb17496d",
          "md5": "ec45a6da506d8c02f7192e029ca8aece"
        }
      ]
    },
    {
      "name": "windowsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-windows-1.0.3-sources.jar",
          "url": "kni-api-windows-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
