{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.1/kni-api-1.0.1.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeX86Main-1.0.1.klib",
          "url": "kni-api-androidnativex86-1.0.1.klib",
          "size": 314079,
          "sha512": "8d4152689e3433883bff53d82015cf612de8f17a8333d17160f86dc3686236ae8b3ab18efa676aeee9db834e967c692f42972564d6ea6e2bca80ffbafbad5adb",
          "sha256": "dbe073f025c7a577b2742e1490657a100b2389baba5ec461a9f36b98e629f583",
          "sha1": "c94971849a8cd32c6c0028c3181b9227e2de6447",
          "md5": "41a71b0d83623ee92eb86e76ecd1887d"
        },
        {
          "name": "kni-api-androidNativeX86Cinterop-jniMain-1.0.1.klib",
          "url": "kni-api-androidnativex86-1.0.1-cinterop-jni.klib",
          "size": 16405,
          "sha512": "14e57b06a151286481f5b1bca4e36481d33b92a4a9d6ef651fdad6de88546c1f304026bd0be4ad279e97849f905ecba8b2ae9ff457183577a5b49b0080a7e5c6",
          "sha256": "2819ea3bfd644092f316a2ce7dc6c2ddda1d33298986c27ef3bca211ca010aad",
          "sha1": "848eb10c3d77c93bd90a5ff196311f314cab8ef5",
          "md5": "bf61918010fd1a2984f7c90cb061a1fb"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativex86-1.0.1-sources.jar",
          "url": "kni-api-androidnativex86-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "5bbb9c63d40f26289ac620c83bc4af3498a2640b886c5e02070220397299dc2d4231f374d06bb3534290f5b750c6124510fbb9351ba3e505544ba17f8eedf561",
          "sha256": "6af75a865ba406e04cc85a3debe889812302cf880f589689447617b8a5a450f2",
          "sha1": "13c9dd629bcd18808fb03a680125e21676332fa9",
          "md5": "e0222a14c24a77f52c50a994f198e1ae"
        }
      ]
    }
  ]
}
