{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-metadata-1.0.2.jar",
          "url": "kni-api-1.0.2.jar",
          "size": 68567,
          "sha512": "e5c1fb339c65ea29c51cf293aa2b57b4484bc381cfd62a6fc0b07365974dfaf39021bd8bf9e0971f6c94609907d9250c9921c0c22e6518270b0eec18ae8e2bd5",
          "sha256": "be3c55e8ec7810ba0e81515d2fb905b81da3da0784ff3cf5dfbd002a2f6c68aa",
          "sha1": "38765762a632ed5c0695dd0173049c02355c90ff",
          "md5": "72dfa5932cc9049f1e5d747f20567c4e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kni-api-kotlin-1.0.2-sources.jar",
          "url": "kni-api-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "b7b0079ffd57136c5e9895d1462de8e58d803897d06f37103b5c5c6c0a9dfaa9cee85c623072353f92550f3d7d358937751be37499a165c2846176ef7704c087",
          "sha256": "8a95837d938ebdc87badbebdf0613769f5de2d5e0e0dde9d2242fac41c074868",
          "sha1": "7a24701bf77a101e67cc98e0208aa21dace93245",
          "md5": "b4f494f6afae3160d0c0595b06b763ad"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.2/kni-api-android-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.2/kni-api-android-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.2/kni-api-android-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm32/1.0.2/kni-api-androidnativearm32-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm32",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm32/1.0.2/kni-api-androidnativearm32-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm32",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm64/1.0.2/kni-api-androidnativearm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm64/1.0.2/kni-api-androidnativearm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex64/1.0.2/kni-api-androidnativex64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex64",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex64/1.0.2/kni-api-androidnativex64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex64",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex86/1.0.2/kni-api-androidnativex86-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex86",
        "version": "1.0.2"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex86/1.0.2/kni-api-androidnativex86-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex86",
        "version": "1.0.2"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.2/kni-api-desktop-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.2/kni-api-desktop-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.2/kni-api-desktop-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.2/kni-api-iosarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.2/kni-api-iosarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.2/kni-api-iosarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.2/kni-api-iossimulatorarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.2/kni-api-iossimulatorarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.2/kni-api-iossimulatorarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.2/kni-api-iosx64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.2/kni-api-iosx64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.2/kni-api-iosx64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.2/kni-api-macosarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.2/kni-api-macosarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.2/kni-api-macosarm64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.2/kni-api-macosx64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.2/kni-api-macosx64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.2/kni-api-macosx64-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-windows/1.0.2/kni-api-windows-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-windows",
        "version": "1.0.2"
      }
    },
    {
      "name": "windowsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-windows/1.0.2/kni-api-windows-1.0.2.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-windows",
        "version": "1.0.2"
      }
    }
  ]
}
