{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosX64Main-1.0.3.klib",
          "url": "kni-api-iosx64-1.0.3.klib",
          "size": 311802,
          "sha512": "0edb6897627561965c3e9b4f49a6686443be6bb8f3eb4753f90dfc9eccc68b535154b3a643461064dfc34e3d6b13b4dae5f5d17c7042b093f2c5a5d780c234a8",
          "sha256": "7c18973b9dd9ff6b4c522cfc37208480bb0e5b2a2a2e74a03d712593149a41f7",
          "sha1": "aa8ed912c555d2739beea4d62c34ba6d94fb525f",
          "md5": "e5d6b3e844d4a684cb224cab8baf683d"
        },
        {
          "name": "kni-api-iosX64Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-iosx64-1.0.3-cinterop-jni.klib",
          "size": 16413,
          "sha512": "cd12eeb8b468f86666bb9c03de95d47f111480fa2d4049cf2df81c2716c2c7b9f543fb470a1251d4a027f392d194fdd83363e420551d69251f272c672798de12",
          "sha256": "de34deb5b3d1c0d39ecc47038f6091c554c8f6114e2f05f786c243f5e8552ce9",
          "sha1": "741dc34b0436c57bdea445c22177ac0924a4439c",
          "md5": "6c407919cae15f6de489822f442b445b"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iosx64-1.0.3-sources.jar",
          "url": "kni-api-iosx64-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosx64-1.0.3-metadata.jar",
          "url": "kni-api-iosx64-1.0.3-metadata.jar",
          "size": 33701,
          "sha512": "cebff3d219a775beeb73b1c77b03e6dcd7387509abbac1bd63ae14ae9b19234ef5087e912fab308c4b5c3ae9665aaa99c9cf01266ea20941a517a3ac0e844fb8",
          "sha256": "edfd24c7c921c147cced09e3c64ae6a51cb3661b41fc5718555064286043a289",
          "sha1": "9373a373f087d245b7758439fbe9586f8985815a",
          "md5": "c4a65a73fb0ad650aedf8c20478b1011"
        }
      ]
    }
  ]
}
