{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeX86Main-1.0.2.klib",
          "url": "kni-api-androidnativex86-1.0.2.klib",
          "size": 317643,
          "sha512": "7b0aa4d9ca1b5da609da6908db6dec23a4683dbb05fc27062da3788463c3d5c724d42771ec953a5ec78519a97760157c374c1989a2fa0531f47ecebd7a3b7ac6",
          "sha256": "8beaf5dd6a3e7438a8224420c9e22220a4aea6cd6e4308ff458474683fa2bf51",
          "sha1": "2d5fed3223247a1c4a86be09aa2d2bf493eb0590",
          "md5": "cb9106403a6b01a90e1d8639190e3c45"
        },
        {
          "name": "kni-api-androidNativeX86Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-androidnativex86-1.0.2-cinterop-jni.klib",
          "size": 16405,
          "sha512": "14e57b06a151286481f5b1bca4e36481d33b92a4a9d6ef651fdad6de88546c1f304026bd0be4ad279e97849f905ecba8b2ae9ff457183577a5b49b0080a7e5c6",
          "sha256": "2819ea3bfd644092f316a2ce7dc6c2ddda1d33298986c27ef3bca211ca010aad",
          "sha1": "848eb10c3d77c93bd90a5ff196311f314cab8ef5",
          "md5": "bf61918010fd1a2984f7c90cb061a1fb"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativex86-1.0.2-sources.jar",
          "url": "kni-api-androidnativex86-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
