{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.1/kni-api-1.0.1.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeX64Main-1.0.1.klib",
          "url": "kni-api-androidnativex64-1.0.1.klib",
          "size": 314079,
          "sha512": "7b1493e13f02bdca396d9c225603d52c2bc1c5fc9be66ccbfd44ec4a54741952024e288c246ea53b9300b51f235278e6e92c7998d3da68276080ab4cd46c5830",
          "sha256": "f9bb0eaa7fba27363710c873dbe89746a95d80c394dccc8e2e891deee912e4db",
          "sha1": "dceec64049cd19aab29d2e37d6b8ab65e786a821",
          "md5": "20f40f1f0351ff069ebbffaf379fdd2f"
        },
        {
          "name": "kni-api-androidNativeX64Cinterop-jniMain-1.0.1.klib",
          "url": "kni-api-androidnativex64-1.0.1-cinterop-jni.klib",
          "size": 16381,
          "sha512": "05ade1301a08b6f39fe9b96d18dc9c57d13cde93457c7714baa09aed0a99026e6fb1eeb805efdd083f0e5616d67bdb8e603ad0f69ce10bb69abd12b226e2518d",
          "sha256": "857aa4ea4027e7ffced78db366b1f99af9f689360fb6d83e9650e495d044d5fb",
          "sha1": "8b40feaaf0af6473c490d54f3fd14aa7891b21c1",
          "md5": "641f3cfeb7d6b725338f933830d12d0c"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativex64-1.0.1-sources.jar",
          "url": "kni-api-androidnativex64-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "5bbb9c63d40f26289ac620c83bc4af3498a2640b886c5e02070220397299dc2d4231f374d06bb3534290f5b750c6124510fbb9351ba3e505544ba17f8eedf561",
          "sha256": "6af75a865ba406e04cc85a3debe889812302cf880f589689447617b8a5a450f2",
          "sha1": "13c9dd629bcd18808fb03a680125e21676332fa9",
          "md5": "e0222a14c24a77f52c50a994f198e1ae"
        }
      ]
    }
  ]
}
