{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "service",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "nio",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api.aar",
          "url": "kni-api-android-1.0.2.aar",
          "size": 92977,
          "sha512": "53f59d0e8627afd228fa85f8536993cbe5dcc98bc3eaab4f3f09148147ffcded56833f6e0d69626b6ec394fb24c74f887716f3dc57a7003a23c82974ca7e9305",
          "sha256": "9f91e794cbccd8923e1c2bf24cb5b3996f45a819a7cac14bf1f1a14e37beeb91",
          "sha1": "d6294a291d696fdf2ed30e38be8fee8f40a7aa9a",
          "md5": "ed31eca1c130220150a15f2ab4758978"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "core",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "service",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "nio",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.github.dreammooncai.yukireflection",
          "module": "api-kotlin",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api.aar",
          "url": "kni-api-android-1.0.2.aar",
          "size": 92977,
          "sha512": "53f59d0e8627afd228fa85f8536993cbe5dcc98bc3eaab4f3f09148147ffcded56833f6e0d69626b6ec394fb24c74f887716f3dc57a7003a23c82974ca7e9305",
          "sha256": "9f91e794cbccd8923e1c2bf24cb5b3996f45a819a7cac14bf1f1a14e37beeb91",
          "sha1": "d6294a291d696fdf2ed30e38be8fee8f40a7aa9a",
          "md5": "ed31eca1c130220150a15f2ab4758978"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kni-api-android-1.0.2-sources.jar",
          "url": "kni-api-android-1.0.2-sources.jar",
          "size": 18205,
          "sha512": "41249db225fa34f1275566e1588a7e1f5847f8fbf15c20a6872c3229b3e28ba670762c230d73cd8d24836354d6c83079b6328b26049cb1c0cfb2bd4b8355b625",
          "sha256": "8c6ce82d8dfbd9b6182d6fb37b4b7f3d49f4036eecfd207c71c820f0fdac0dd4",
          "sha1": "14524687946bd9f7088ecd905da40c1728273eea",
          "md5": "1ac138564c1528a24ca5f758b031ba8a"
        }
      ]
    }
  ]
}
