{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-desktop-1.0.3.jar",
          "url": "kni-api-desktop-1.0.3.jar",
          "size": 29658,
          "sha512": "8a8ab26c13bec0e80c3cba6d8e4ca27d3dad79860688e37e7a234501415266cc633ac9f3a81b1088aa0efcc3d7d5920db48f6f3a0adce3586b28a73dc4cd54f6",
          "sha256": "911f780e8e217e50d5f465d333ba67dabe8e2dcb3ec65b59ac15b756f5ae8521",
          "sha1": "7100c840caa03e7a0b97e87e6511ec738f20fac9",
          "md5": "f33e37ab8704e0d29137172202e12820"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-desktop-1.0.3.jar",
          "url": "kni-api-desktop-1.0.3.jar",
          "size": 29658,
          "sha512": "8a8ab26c13bec0e80c3cba6d8e4ca27d3dad79860688e37e7a234501415266cc633ac9f3a81b1088aa0efcc3d7d5920db48f6f3a0adce3586b28a73dc4cd54f6",
          "sha256": "911f780e8e217e50d5f465d333ba67dabe8e2dcb3ec65b59ac15b756f5ae8521",
          "sha1": "7100c840caa03e7a0b97e87e6511ec738f20fac9",
          "md5": "f33e37ab8704e0d29137172202e12820"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kni-api-desktop-1.0.3-sources.jar",
          "url": "kni-api-desktop-1.0.3-sources.jar",
          "size": 7909,
          "sha512": "a3a815cc68f6aa20459becce21630699121f0c53428d711fd1d61993138b78149a05a001e10b745b8745b8d1ec231e05df0bc35add660a7b8795a214f6440f6d",
          "sha256": "d8873598fab012cfd806099949df805949e99e53ebcbad4ab7a0f21d49f0a7bb",
          "sha1": "e16fac4f2ee627f586a187bc173c47fb08f9a36f",
          "md5": "73a116a31051888d239a8699a9368d47"
        }
      ]
    }
  ]
}
