{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeArm64Main-1.0.3.klib",
          "url": "kni-api-androidnativearm64-1.0.3.klib",
          "size": 311835,
          "sha512": "1f288bcb9c6d51d23cf9162d596a3d487cc5369fc882e83bbf602ecff6549b33f2fae47ab3f93ecf87ca60c0f3d193126ec49c0030bb60be6f773e29641db2d6",
          "sha256": "5d150f46067dec48d6bd3888efcfc9ba8b88ef48890dfdfdb736c313e098fc94",
          "sha1": "e0446244c18f7805f1f2bc0fb45418320e8235c9",
          "md5": "c1e0be8579cfe12303a9a30cebc7b8f1"
        },
        {
          "name": "kni-api-androidNativeArm64Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-androidnativearm64-1.0.3-cinterop-jni.klib",
          "size": 16350,
          "sha512": "818126770b8958b0db91593affb791d5cf57d176ffc65b92b0c05c971a92c122e08a0f42497f51397f464154d5767d15100420145686fa0925216f7b50410f25",
          "sha256": "2acacf1fa0afbea642b69c3d5995aa6f3bc56f4c955c93d1a9701d9edb9146d9",
          "sha1": "dc9fd7f7ed1d919b300c04b87e0c59ef67b8d27e",
          "md5": "53dcb25a0372b2efbc902cf1d31e0163"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativearm64-1.0.3-sources.jar",
          "url": "kni-api-androidnativearm64-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
