{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosSimulatorArm64Main-1.0.3.klib",
          "url": "kni-api-iossimulatorarm64-1.0.3.klib",
          "size": 311881,
          "sha512": "487f510d59e0dc24d843ee403e9a9857eef3df11ed98944b5fa2f855141bace57404cd58862a1d8025b487eb396e1b508f001e4616f07c901dcf8710eafeb887",
          "sha256": "331d445b78370ff04f97f85cf1cd33e99caafdc9bdf7d54cae0af513a2aa7d1c",
          "sha1": "f3cdb17d548902d2ae351d8f1ba0a972596f6533",
          "md5": "9ff67cb50531500a8d5e71d2f622d537"
        },
        {
          "name": "kni-api-iosSimulatorArm64Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-iossimulatorarm64-1.0.3-cinterop-jni.klib",
          "size": 16796,
          "sha512": "41ce5c37094fe3b08dbf8002fd5f2609cb57618a5284a3c4762c14dd7fc2a8cd839c19f8a2baa8949c986be05fcacd14654ce2e307df0a40083de69bf04cd425",
          "sha256": "33420fd7e24ca669bb3163639ec7aad243b2b74240469669760b2850ecbe229c",
          "sha1": "9db99ae6a4c7e6ff88484ba807dc0f0770225bf3",
          "md5": "55701bf225df41d848b736a069ed3aeb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iossimulatorarm64-1.0.3-sources.jar",
          "url": "kni-api-iossimulatorarm64-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iossimulatorarm64-1.0.3-metadata.jar",
          "url": "kni-api-iossimulatorarm64-1.0.3-metadata.jar",
          "size": 33701,
          "sha512": "cebff3d219a775beeb73b1c77b03e6dcd7387509abbac1bd63ae14ae9b19234ef5087e912fab308c4b5c3ae9665aaa99c9cf01266ea20941a517a3ac0e844fb8",
          "sha256": "edfd24c7c921c147cced09e3c64ae6a51cb3661b41fc5718555064286043a289",
          "sha1": "9373a373f087d245b7758439fbe9586f8985815a",
          "md5": "c4a65a73fb0ad650aedf8c20478b1011"
        }
      ]
    }
  ]
}
