{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.1/kni-api-1.0.1.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeArm64Main-1.0.1.klib",
          "url": "kni-api-androidnativearm64-1.0.1.klib",
          "size": 314092,
          "sha512": "b3f703a13bfae6d36184369412df7354b00915e4d07de6c2c70d3b49f466b24e2b10935baf43caa4636eeb548944e003043aee620e0852954a8278a700fbd44a",
          "sha256": "b78f23fed18158be975854fd06881d8ad03b0562a76d64b2481fc9ebc439e55e",
          "sha1": "1223889af7c261107e04cdde866964f10589d496",
          "md5": "ccfdb1645120fcacd021d13f55cd565b"
        },
        {
          "name": "kni-api-androidNativeArm64Cinterop-jniMain-1.0.1.klib",
          "url": "kni-api-androidnativearm64-1.0.1-cinterop-jni.klib",
          "size": 16348,
          "sha512": "04268f3843698de4b70186e5bc96adabd5d2252f0ddab3cebdda461305ad0baf13241331bf359d81892d7de9865ebf0aec8497e3d0183706112b7437d1bd5f33",
          "sha256": "e9007e1f3aeaa5dc9b0636746a722bcbeb48edb521670d138c5540ffed47ba12",
          "sha1": "fa103ecdb88c287dec591a49c34a5a278ee22ec5",
          "md5": "9540051ac4ed7b6a7aa601d47da56161"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativearm64-1.0.1-sources.jar",
          "url": "kni-api-androidnativearm64-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "5bbb9c63d40f26289ac620c83bc4af3498a2640b886c5e02070220397299dc2d4231f374d06bb3534290f5b750c6124510fbb9351ba3e505544ba17f8eedf561",
          "sha256": "6af75a865ba406e04cc85a3debe889812302cf880f589689447617b8a5a450f2",
          "sha1": "13c9dd629bcd18808fb03a680125e21676332fa9",
          "md5": "e0222a14c24a77f52c50a994f198e1ae"
        }
      ]
    }
  ]
}
