{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.3/kni-api-1.0.3.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "8.0.01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeX86Main-1.0.3.klib",
          "url": "kni-api-androidnativex86-1.0.3.klib",
          "size": 311822,
          "sha512": "e4e48baa8039220f7ef4ddf6bff8a81e5144bb2fe5bf8112200480ebd11d7950daacc71fb705438531193e181c669cdd34267187ad8302e1c91de7518b0b886f",
          "sha256": "b678acaa03feb65f3f78feeab1692c387d07b453223927f3c60ba2322547cca5",
          "sha1": "4efea17cfe61461e3fadcc4dad8f60c6974f829a",
          "md5": "cd31646fd07f25ec6e6b4dfd4c22499a"
        },
        {
          "name": "kni-api-androidNativeX86Cinterop-jniMain-1.0.3.klib",
          "url": "kni-api-androidnativex86-1.0.3-cinterop-jni.klib",
          "size": 16407,
          "sha512": "1adc29bb359ae094228fa9f0bdf4838cddc70c90bfeb6648b41f06d304a5d2d3be90bad5ce10b7727591dbe5ea784f6e6b1a9a7c140c1679c147355510a4c620",
          "sha256": "62c10694a26b7ca3698d6922fdb6166029c46c347ffb2705c6fbd79cbe49888b",
          "sha1": "1684e48586fa2a0400a5c23d5adc85242ca85b45",
          "md5": "943366452aee0b62785ee467862188f1"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativex86-1.0.3-sources.jar",
          "url": "kni-api-androidnativex86-1.0.3-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
