{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeArm32Main-1.0.2.klib",
          "url": "kni-api-androidnativearm32-1.0.2.klib",
          "size": 317654,
          "sha512": "30b1a22b8c6c765202d30152420debd54574bb21cede734473d2f93ae9c07f5c4d65beff857ca8d0027acd5e5c1c1d602f6171cbd96f5635702a39c4c6253860",
          "sha256": "ececb25850869e6873e449c29600c9618b4b81641f6354788bec0bdab0d630a4",
          "sha1": "e6a2144eb8ed58463e728f583f3bc81527354942",
          "md5": "8332f293cfb2f5c931993c212436e17c"
        },
        {
          "name": "kni-api-androidNativeArm32Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-androidnativearm32-1.0.2-cinterop-jni.klib",
          "size": 16635,
          "sha512": "9716a202fb8826b18564fef22eaff7aae2f0727b00a95b5175dac9e6b09028c86ed98752fb8fb5a38ed1bc60ccad4bbd1fbf73a4f5488df16c1e45125157b38d",
          "sha256": "c3cb795bea208f25526c00e35f839e679111713d52ab8952f230991f02fe3f7c",
          "sha1": "b400f361c6e76636406a8f828aca54c8a554c23b",
          "md5": "df0ea5e74712aa3d063412d7d48fc24a"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativearm32-1.0.2-sources.jar",
          "url": "kni-api-androidnativearm32-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
