{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-androidNativeArm64Main-1.0.2.klib",
          "url": "kni-api-androidnativearm64-1.0.2.klib",
          "size": 317656,
          "sha512": "a338de262b4efd20481af385627172972956828bb8a951ddba028e736974c46485fb06ec4fa97952df28fbee9c6b84e4c23b5cfcba988b932d98ea5d30c39f86",
          "sha256": "48c185850e33bf22e5db45de0da61f59e580954304cbfb116985c67ad98f7c44",
          "sha1": "26db277b7ad4c62f82648746b2f2d24618b942da",
          "md5": "b81c180948c28a30b164ffe03daa95ad"
        },
        {
          "name": "kni-api-androidNativeArm64Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-androidnativearm64-1.0.2-cinterop-jni.klib",
          "size": 16348,
          "sha512": "04268f3843698de4b70186e5bc96adabd5d2252f0ddab3cebdda461305ad0baf13241331bf359d81892d7de9865ebf0aec8497e3d0183706112b7437d1bd5f33",
          "sha256": "e9007e1f3aeaa5dc9b0636746a722bcbeb48edb521670d138c5540ffed47ba12",
          "sha1": "fa103ecdb88c287dec591a49c34a5a278ee22ec5",
          "md5": "9540051ac4ed7b6a7aa601d47da56161"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-androidnativearm64-1.0.2-sources.jar",
          "url": "kni-api-androidnativearm64-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    }
  ]
}
