{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-desktop-1.0.2.jar",
          "url": "kni-api-desktop-1.0.2.jar",
          "size": 33057,
          "sha512": "c0ed4aed596fa523e136f6ddd835b23b346b6c30c1c183c559536a776d13d5e35f07002228e048e4de4c069fe4fdfacccf0c3bd583832d552789e429d607100e",
          "sha256": "5c6a677266d1c9541406fe32156d276f8ca4e7160bc18c88178a1cdbfb442246",
          "sha1": "a9843bda3921a7ca1402a78e65cd170ab97e34ea",
          "md5": "dcf0712228b68241b0fd39d8251ba7df"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-desktop-1.0.2.jar",
          "url": "kni-api-desktop-1.0.2.jar",
          "size": 33057,
          "sha512": "c0ed4aed596fa523e136f6ddd835b23b346b6c30c1c183c559536a776d13d5e35f07002228e048e4de4c069fe4fdfacccf0c3bd583832d552789e429d607100e",
          "sha256": "5c6a677266d1c9541406fe32156d276f8ca4e7160bc18c88178a1cdbfb442246",
          "sha1": "a9843bda3921a7ca1402a78e65cd170ab97e34ea",
          "md5": "dcf0712228b68241b0fd39d8251ba7df"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kni-api-desktop-1.0.2-sources.jar",
          "url": "kni-api-desktop-1.0.2-sources.jar",
          "size": 7424,
          "sha512": "1ec8bcbf79e98e5d0e6df6cf2279a79e9be59297bb1f03c4ec8f818ce5e087d0ba9236bd673573a83187e9a371809266800ea6eb1c4ad1b4f3df233cbf2019eb",
          "sha256": "e9bfd1a94c8aab2fbc251af7f202c0b6eebfd1207a8e6d6f50a387a9df75fbf6",
          "sha1": "6b279371f6edb76145e6f311f861d96be3d0bbab",
          "md5": "8791557db66c420fbb839a63be2c3bd7"
        }
      ]
    }
  ]
}
