{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosArm64Main-1.0.2.klib",
          "url": "kni-api-macosarm64-1.0.2.klib",
          "size": 317643,
          "sha512": "ddda7ed3b9ef56d71c4307ebab9fa23d367795cb394e9c839a9d38afc3c681a3c48654c84c57e3bfe87646f83efa38c30c3592c9b72c72be1d8c0ae31895d0c2",
          "sha256": "0b56a35c3709f41c9fa4be6e42f5512500c0dd5f793a7195180ca6449e4e6a33",
          "sha1": "7ef9f8ee14314e2a67da18afd65c941e521550e8",
          "md5": "4c400bf952a1d890d54bf91a1e5dbf2f"
        },
        {
          "name": "kni-api-macosArm64Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-macosarm64-1.0.2-cinterop-jni.klib",
          "size": 16701,
          "sha512": "ab8426bc266927e8a5c93c15f967436b0ec80bd8603b7ad9ed422e8ae86065aa0e68fbb80f2a79eaacebc1e98ad9e61015fbcb9aac22bc683841f6addbccf63e",
          "sha256": "8e4ba882dff494a8131c3274574d4cb28d009a265d3e248c7b7f63d9b18eb6c0",
          "sha1": "f457aac1bb6fcd9131148f54af62affc6ec94837",
          "md5": "d396ec3efc1be06706db2efe7081b8a1"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-macosarm64-1.0.2-sources.jar",
          "url": "kni-api-macosarm64-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-macosarm64-1.0.2-metadata.jar",
          "url": "kni-api-macosarm64-1.0.2-metadata.jar",
          "size": 33688,
          "sha512": "0701d2a43aa422911b35246e62c545ff39a367c5c020b5def576ff77b63c93f32b7fe95728fd362934c587fcf9ffca387718a62a12033c02b24e0885e5fdba73",
          "sha256": "a451b1441d78dc651f4cf267d1beefb038463efe091d9945ebf2b022259b17f6",
          "sha1": "425b3afd91defbf5a46c77ceef2b9121f956fe3e",
          "md5": "5060618924aefaa8d0955ac09ce59096"
        }
      ]
    }
  ]
}
