{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kni-api/1.0.2/kni-api-1.0.2.module",
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iosSimulatorArm64Main-1.0.2.klib",
          "url": "kni-api-iossimulatorarm64-1.0.2.klib",
          "size": 317694,
          "sha512": "edd8bfb133d22620e4ef05b0b81f1d27fbd7865b4b140ea61a23ae2ac419da14a7c4e84e91bbcc91847c72d7553ce99ee22473d2b16740e8d5f5420ff5bc920d",
          "sha256": "5f86e1ffaa514586432e169665cc738002ce39c50b4441a741e5d45f3ed44ff8",
          "sha1": "4db636145297d89c388810aa098390319420ddc2",
          "md5": "5af911d43130635c10310622d96b3ad7"
        },
        {
          "name": "kni-api-iosSimulatorArm64Cinterop-jniMain-1.0.2.klib",
          "url": "kni-api-iossimulatorarm64-1.0.2-cinterop-jni.klib",
          "size": 16795,
          "sha512": "2f71f6e076efe371636ad612e8c61ec57767eca5fd5531fa90878358d88e0a3644dc8d371bd83fcd162c6ea7f8d9710cd36dc5374a5097a0f7c8e75610c5bb34",
          "sha256": "154ad64e47fb1f98ae545a153b56f2fe6773d4efd70e56d3149b19c8a3d53a68",
          "sha1": "a290a1ef1ffe2789f78e797b03540a2809a79c0e",
          "md5": "053b699c6370650cd86a2c5f07d37211"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kni-api-iossimulatorarm64-1.0.2-sources.jar",
          "url": "kni-api-iossimulatorarm64-1.0.2-sources.jar",
          "size": 41766,
          "sha512": "3f4e9ce75a99082334fcc02d3dd4599e17bfe76894bb64378fee0ed587b3693e2d02c97693dc3b63eb5f17e273886ea31d20f3465c4e47687a1e20596cf93649",
          "sha256": "6b4bb34915d06b5395272b93efbdd265be209f790daaba3c172c9b5348ee8fb6",
          "sha1": "f613101d30e12a4ab0638e427e2434ae455269e0",
          "md5": "f5aa7f1d0bd35fcf0719a24abbf1fa4c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-iossimulatorarm64-1.0.2-metadata.jar",
          "url": "kni-api-iossimulatorarm64-1.0.2-metadata.jar",
          "size": 33688,
          "sha512": "8fe1b37bdad17c4aa3f6d3d558383ec4797ea8963452f66c4b2ab9cacd016e8be5cc3e615537e9813ea5c4c9815322afb1cd22e571326f7bbd30cd27d46c3ff5",
          "sha256": "472fe99cb721c21ce6999624087765ff4aca61ab4b0b4a5bf3025c1aadff7b69",
          "sha1": "bfb998d43dd96ac461e0e6c0c8f683095bc1cbed",
          "md5": "eb77763a41aacbf4ac0b958019da6148"
        }
      ]
    }
  ]
}
