{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dreammooncai",
    "module": "kni-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.dreammooncai",
          "module": "multiplatform-everything",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kni-api-metadata-1.0.1.jar",
          "url": "kni-api-1.0.1.jar",
          "size": 68117,
          "sha512": "98eccc6bca1192822e7e2116af8a1dab08282f5301a500ceb9bbb89e681a43ddaf7b54119645cc508ec10ba83ddba7637bc0ca1d2fcb9c888e9920018993f381",
          "sha256": "a9631ba9820e58103da4826b86bbbd5e6e6e8f4eaacd3b8fe1dbf0d238da5245",
          "sha1": "bcfe9ac40cca8838c581ee8632b20650dd235c35",
          "md5": "2e2e535d1dfe81611b1ef549315b9b69"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kni-api-kotlin-1.0.1-sources.jar",
          "url": "kni-api-1.0.1-sources.jar",
          "size": 41202,
          "sha512": "02e00d5d9a9323827f5668b7170386f846213bb881ee87b04212f5a78a380389c19e51cb2a09ee21d07b0014d9ff1a1a4963c125727d01b20ed1d2706c9be231",
          "sha256": "a4cc42d982005d3c5434cd76b7cf9da4439a92b0bf08068876773c688ad9cf96",
          "sha1": "ca9b02bdfca2b985325f5811e3df65686286a8d0",
          "md5": "fbba9286ce84882b654344076cf5920f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.1/kni-api-android-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.1/kni-api-android-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-android/1.0.1/kni-api-android-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-android",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm32/1.0.1/kni-api-androidnativearm32-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm32",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm32/1.0.1/kni-api-androidnativearm32-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm32",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm64/1.0.1/kni-api-androidnativearm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativearm64/1.0.1/kni-api-androidnativearm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativearm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex64/1.0.1/kni-api-androidnativex64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex64",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex64/1.0.1/kni-api-androidnativex64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex64",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex86/1.0.1/kni-api-androidnativex86-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex86",
        "version": "1.0.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-androidnativex86/1.0.1/kni-api-androidnativex86-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-androidnativex86",
        "version": "1.0.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.1/kni-api-desktop-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.1/kni-api-desktop-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kni-api-desktop/1.0.1/kni-api-desktop-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-desktop",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.1/kni-api-iosarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.1/kni-api-iosarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosarm64/1.0.1/kni-api-iosarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.1/kni-api-iossimulatorarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.1/kni-api-iossimulatorarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iossimulatorarm64/1.0.1/kni-api-iossimulatorarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.1/kni-api-iosx64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.1/kni-api-iosx64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-iosx64/1.0.1/kni-api-iosx64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-iosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.1/kni-api-macosarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.1/kni-api-macosarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosarm64/1.0.1/kni-api-macosarm64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.1/kni-api-macosx64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.1/kni-api-macosx64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-macosx64/1.0.1/kni-api-macosx64-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-macosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "windowsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-windows/1.0.1/kni-api-windows-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-windows",
        "version": "1.0.1"
      }
    },
    {
      "name": "windowsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kni-api-windows/1.0.1/kni-api-windows-1.0.1.module",
        "group": "io.github.dreammooncai",
        "module": "kni-api-windows",
        "version": "1.0.1"
      }
    }
  ]
}
